version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - checkout
      - run:
          name: Node version
          command: node --version
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Run Test
          command: yarn run test

workflows:
  test-deploy:
    jobs:
      - build
      