version: 2.1

orbs:
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install and make 1
          command: yarn && make test-coverage-1
      - run:
          name: Run tests
          command: yarn run test
      - coveralls/upload
      

workflows:
  test-deploy:
    jobs:
      - build

notify:
  webhooks:
    - url: https://coveralls.io/webhook?repo_token=${process.env.COVERALLS_REPO_TOKEN}