version: 2.1

orbs:
  node: circleci/node@5.0.0
  coveralls: coveralls/coveralls@1.0.6

jobs:
  build:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: test
          command: yarn run test
      - run:
          name: code-coverage
          command: yarn run coverage
      - coveralls/upload

workflows:
  test-deploy:
    jobs:
      - build
      