version: 2.1

jobs:
  test:
    docker:
      - image: cimg/node:17.6.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: Installing dependency
          command: yarn
      - run:
          name: Run tests
          command: yarn run test



workflows:
  test-deploy:
    jobs:
      - test